spring:
  application:
    name: peerping-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/peerping
    username: peerping
    password: peerping123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-only-change-in-production}
      access-token-expiration: 1800000 # 30 minutes
      refresh-token-expiration: 2592000000 # 30 days

server:
  port: 8080
  servlet:
    context-path: /v1
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.peerping: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator