1server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/peerly}
    username: ${DB_USER:peerly}
    password: ${DB_PASS:peerly}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-here-for-development-only}
    ttlSeconds: 86400

cors:
  allowed-origins:
    - http://localhost:19006
    - http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics